services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - data:/data
      - letsencrypt:/etc/letsencrypt
  idiotita-poker:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "1500"
    environment:
      - DISCORD_TOKEN=
      - CLIENT_ID=
      - CLIENT_SECRET=
      - GUILD_ID_BITMEX=
      - DB_PATH=
      - PORT=
      - ROLE_ADMIN=
    volumes:
      - data-volume:/app/data
  twitch-auth:
    image: twitch-auth:latest
    restart: unless-stopped
    expose:
      - "3000"
    environment:
      - PORT=
      - CLIENT_ID=
      - CLIENT_SECRET=
      - URL_URI=
      - DB_PATH=
    volumes:
      - data-volume:/app/data
volumes:
  data-volume:
  data:
  letsencrypt: